export const ACCOUNT_GROUP_REQUEST = 'ACCOUNT_GROUP_REQUEST';
export const ACCOUNT_GROUP_SUCCESS = 'ACCOUNT_GROUP_SUCCESS';
export const ACCOUNT_GROUP_FAIL = 'ACCOUNT_GROUP_FAIL';

export const ADD_ACCOUNT_REQUEST = 'ADD_ACCOUNT_REQUEST';
export const ADD_ACCOUNT_SUCCESS = 'ADD_ACCOUNT_SUCCESS';
export const ADD_ACCOUNT_FAIL = 'ADD_ACCOUNT_FAIL';

export const ACCOUNT_GROUP_LIST_REQUEST = 'ACCOUNT_GROUP_LIST_REQUEST';
export const ACCOUNT_GROUP_LIST_FAIL = 'ACCOUNT_GROUP_LIST_FAIL';
export const ACCOUNT_GROUP_LIST_SUCCESS = 'ACCOUNT_GROUP_LIST_SUCCESS';

