export const ADD_DISTRICT_REQUEST = 'ADD_DISTRICT_REQUEST';
export const ADD_DISTRICT_SUCCESS = 'ADD_DISTRICT_SUCCESS';
export const ADD_DISTRICT_FAIL = 'ADD_DISTRICT_FAIL';

export const DISTRICT_LIST_REQUEST = 'DISTRICT_LIST_REQUEST';
export const DISTRICT_LIST_FAIL = 'DISTRICT_LIST_FAIL';
export const DISTRICT_LIST_SUCCESS = 'DISTRICT_LIST_SUCCESS';


export const DISTRICT_DETAILS_FAIL = 'DISTRICT_DETAILS_FAIL';
export const DISTRICT_DETAILS_REQUEST = 'DISTRICT_DETAILS_REQUEST';
export const DISTRICT_DETAILS_SUCCESS = 'DISTRICT_DETAILS_SUCCESS';