export const PRODUCT_GROUP_REQUEST = 'PRODUCT_GROUP_REQUEST';
export const PRODUCT_GROUP_SUCCESS = 'PRODUCT_GROUP_SUCCESS';
export const PRODUCT_GROUP_FAIL = 'PRODUCT_GROUP_FAIL';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const PRODUCT_GROUP_LIST_REQUEST = 'PRODUCT_GROUP_LIST_REQUEST';
export const PRODUCT_GROUP_LIST_FAIL = 'PRODUCT_GROUP_LIST_FAIL';
export const PRODUCT_GROUP_LIST_SUCCESS = 'PRODUCT_GROUP_LIST_SUCCESS';

