export const ADD_SERVICE_REQUEST = 'ADD_SERVICE_REQUEST';
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';
export const ADD_SERVICE_FAIL = 'ADD_SERVICE_FAIL';

export const SERVICE_GROUP_LIST_REQUEST = 'SERVICE_GROUP_LIST_REQUEST';
export const SERVICE_GROUP_LIST_FAIL = 'SERVICE_GROUP_LIST_FAIL';
export const SERVICE_GROUP_LIST_SUCCESS = 'SERVICE_GROUP_LIST_SUCCESS';


export const SERVICE_GROUP_REQUEST = 'SERVICE_GROUP_REQUEST';
export const SERVICE_GROUP_SUCCESS = 'SERVICE_GROUP_SUCCESS';
export const SERVICE_GROUP_FAIL = 'SERVICE_GROUP_FAIL';
