export const ADD_TALUKA_REQUEST = 'ADD_TALUKA_REQUEST';
export const ADD_TALUKA_SUCCESS = 'ADD_TALUKA_SUCCESS';
export const ADD_TALUKA_FAIL = 'ADD_TALUKA_FAIL';

export const TALUKA_LIST_REQUEST = 'TALUKA_LIST_REQUEST';
export const TALUKA_LIST_FAIL = 'TALUKA_LIST_FAIL';
export const TALUKA_LIST_SUCCESS = 'TALUKA_LIST_SUCCESS';


export const TALUKA_DETAILS_FAIL = 'TALUKA_DETAILS_FAIL';
export const TALUKA_DETAILS_REQUEST = 'TALUKA_DETAILS_REQUEST';
export const TALUKA_DETAILS_SUCCESS = 'TALUKA_DETAILS_SUCCESS';